on:
  pull_request:

name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare Laravel Application
      run: cp .env.ci .env

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Run Testsuite
      run: php vendor/bin/testbench package:test

    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@master
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
